# .readthedocs.yaml

version: 2  # Spécifie la version du fichier de configuration

# Définit l'environnement dans lequel la documentation sera construite
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Configuration des fichiers de documentation
sphinx:
  configuration: docs/conf.py  # Fichier de configuration Sphinx à utiliser (par défaut conf.py dans docs/)
