# Generated by Django 3.0 on 2025-04-01 11:03
"""
Migration Django pour la modification du champ 'user' dans le modèle Profile

Cette migration met à jour la relation OneToOne entre Profile et User en ajoutant un related_name
Cela permet d'accéder plus facilement au profil d'un utilisateur via 'user.oc_lettings_profile'
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration modifiant le champ 'user' du modèle Profile
    """
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oc_lettings_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
