# Generated by Django 3.0 on 2025-04-01 11:13
"""
Migration Django pour la suppression des modèles Address, Letting et Profile

Cette migration supprime les champs et les modèles liés à l'application
oc_lettings_site, notamment Address, Letting et Profile, en supprimant d'abord
leurs relations
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration supprimant les modèles Address, Letting et Profile
    """
    dependencies = [
        ('oc_lettings_site', '0002_auto_20250401_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
